name: django-ecommarce

services:
  app:
    build: .
    volumes:
      - .:/django_ecommerce
    ports: 
      - 8000:8000
    image: application:django_ecommerce
    container_name: app_container
    command: python manage.py runserver 0.0.0.0:8000

  inventory_db:
    restart: always
    image: postgres:17.2-alpine3.21
    container_name: inventory_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"