# Generated by Django 5.1.5 on 2025-01-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_image'),
    ]

    operations = [
        migrations.RunSQL(""" 
            ALTER TABLE inventory_schema.django_migrations
            SET SCHEMA inventory_management_schema
     """)
    ]
